import React, { useEffect, useRef } from 'react';
import { storage } from '../services/storage';

export const TOP_NOTIFICATION_SCRIPT_SRC = 'https://pl31050117.profitableratecpmnetwork.com/95/0f/2c/950f2c645a84b149f4ea6fce85d068d2.js';
const NOTIFICATION_INTERVAL_MS = 30000; // 30 seconds interval

// Global window property declaration for singleton lock
declare global {
  interface Window {
    __ROOH_NOTIFICATION_LOCK__?: boolean;
    __ROOH_NOTIFICATION_LAST_INJECT__?: number;
  }
}

export const TopNotificationAd: React.FC = () => {
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    // Check if any ad notification container or floating banner is already visible in the DOM
    const isNotificationCurrentlyVisible = (): boolean => {
      // Check for scripts or containers injected by Profitableratecpm
      const existingScript = document.getElementById('profitableratecpm-top-notification-script');
      
      // Look for DOM elements dynamically generated by network script (floating overlays, social bars, banners)
      const dynamicAdContainers = document.querySelectorAll(
        '[id*="container-950f2c"], [id*="pl31050117"], [class*="profitableratecpm"], [id*="profitableratecpm"], .ad-notification-active'
      );

      if (dynamicAdContainers.length > 0) {
        return true;
      }

      // Check global singleton lock
      if (window.__ROOH_NOTIFICATION_LOCK__) {
        const lastInject = window.__ROOH_NOTIFICATION_LAST_INJECT__ || 0;
        // Keep lock for at least 15 seconds to allow ad rendering and interaction
        if (Date.now() - lastInject < 15000) {
          return true;
        }
      }

      return false;
    };

    // Safe injection function with multi-level duplicate prevention
    const injectAdScript = () => {
      const dev = storage.getDevSettings();
      if (dev.adNetworks?.globalAdsEnabled === false) {
        cleanUpAllAdArtifacts();
        return;
      }

      // 🛑 GUARD 1: Prevent duplicate if already active or visible in DOM
      if (isNotificationCurrentlyVisible()) {
        return;
      }

      // Clean up previous dead script tags before injecting a fresh instance
      cleanUpOldScriptOnly();

      // Set singleton lock
      window.__ROOH_NOTIFICATION_LOCK__ = true;
      window.__ROOH_NOTIFICATION_LAST_INJECT__ = Date.now();

      // Inject single script
      const script = document.createElement('script');
      script.src = TOP_NOTIFICATION_SCRIPT_SRC;
      script.async = true;
      script.setAttribute('data-cfasync', 'false');
      script.id = 'profitableratecpm-top-notification-script';

      script.onload = () => {
        // Unlock after script execution
        setTimeout(() => {
          window.__ROOH_NOTIFICATION_LOCK__ = false;
        }, 10000);
      };

      script.onerror = () => {
        window.__ROOH_NOTIFICATION_LOCK__ = false;
      };

      document.body.appendChild(script);
    };

    const cleanUpOldScriptOnly = () => {
      const existing = document.getElementById('profitableratecpm-top-notification-script');
      if (existing && existing.parentNode) {
        existing.parentNode.removeChild(existing);
      }
    };

    const cleanUpAllAdArtifacts = () => {
      cleanUpOldScriptOnly();
      window.__ROOH_NOTIFICATION_LOCK__ = false;
      // Remove any orphan ad containers if ads get disabled
      const containers = document.querySelectorAll('[id*="container-950f2c"], [id*="profitableratecpm"]');
      containers.forEach(el => el.remove());
    };

    // Initial load check
    injectAdScript();

    // 30-Second interval check (only injects if previous ad is finished and not visible)
    timerRef.current = setInterval(() => {
      injectAdScript();
    }, NOTIFICATION_INTERVAL_MS);

    // Event listeners
    const handleSettingsChange = () => {
      injectAdScript();
    };

    const handleHelpModalTrigger = () => {
      // Force refresh only if not currently visible
      if (!isNotificationCurrentlyVisible()) {
        injectAdScript();
      }
    };

    window.addEventListener('app-settings-changed', handleSettingsChange);
    window.addEventListener('storage', handleSettingsChange);
    window.addEventListener('trigger-top-notification-ad', handleHelpModalTrigger);

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
      window.removeEventListener('app-settings-changed', handleSettingsChange);
      window.removeEventListener('storage', handleSettingsChange);
      window.removeEventListener('trigger-top-notification-ad', handleHelpModalTrigger);
      cleanUpOldScriptOnly();
      window.__ROOH_NOTIFICATION_LOCK__ = false;
    };
  }, []);

  return null;
};
